# Generated by Django 4.2.7 on 2024-02-18 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomap', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='userType',
            field=models.CharField(default='user', max_length=25),
        ),
    ]
