# Generated by Django 4.2.7 on 2024-02-18 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomap', '0002_user_usertype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
