# Generated by Django 5.0.1 on 2024-03-07 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomap', '0004_user_score_user_streak'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_played',
            field=models.DateField(default=None),
        ),
    ]
