# Generated by Django 5.0.1 on 2024-03-07 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomap', '0005_user_last_played'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_played',
            field=models.DateField(default=None, null=True),
        ),
    ]
