# Generated by Django 5.0.1 on 2024-03-15 17:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomap', '0007_word'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('achievement_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
                ('description', models.CharField(max_length=100)),
                ('level_1', models.IntegerField()),
                ('level_2', models.IntegerField()),
                ('level_3', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='UserAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField()),
                ('achievement_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecomap.achievement')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecomap.user')),
            ],
        ),
    ]
