# Generated by Django 5.0.1 on 2024-03-16 23:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomap', '0008_achievement_userachievement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userachievement',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecomap.user', to_field='username'),
        ),
    ]
