# Generated by Django 5.0.2 on 2024-03-20 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomap', '0009_alter_userachievement_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='QrCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
            ],
        ),
    ]
